### ISSUE TITLE
End of video gets confusing

### ISSUE THREAD

**Issue by loganhasson** [learn-co-curriculum/variable-readme#8]
The end of the video becomes a bit unclear when trying to talk about pass by reference/pass by value. Part of it is the variable names (calling something 'reference' and then also talking about 'references'), but also the fact that a description of pass by value/pass by reference is kind of out of the scope of what this lesson is trying to accomplish.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestions.

Generally speaking, the videos are meant as material to augment the written curriculum and should be viewed as optional. After hearing feedback from students wanting more videos we have placed a few throughout the course. Because every student learns differently though, these videos are simply another way to deepen your understanding. If it doesn't work for you that's no problem. To better communicate this we will add a disclaimer explaining all of this to the lessons containing video resources. The written curriculum will independently cover all the required knowledge. Of course, we will continue to improve the videos and written material.

If, after reviewing the written curriculum, you still feel that there is a gap, feel free to reopen the issue.

As always, thanks for contributing! 💙
